.TH SHR_CHOWN 3 SHR-%VERSION%
.SH NAME
.B shr_chown
\- Change the ownership of a shared ring buffer.
.SH SYNOPSIS
.LP
.nf
#include <shr.h>
.P
__attribute__((nonnull))
int shr_chown(const shr_t *restrict \fIshr\fP, uid_t \fIowner\fP, gid_t \fIgroup\fP);
.fi
.P
Link with \fI\-lshr\fP.
.SH DESCRIPTION
The
.BR shr_chown ()
function changes the ownership of a shared ring buffer.
.P
The owner of the shared ring buffer will be set to
\fIowner\fP, and the group will be set to \fIgroup\fP.
.SH RETURN VALUES
Upon successful completion, the function returns 0.
Otherwise the function returns \-1 and sets
\fIerrno\fP to indicate the error.
.SH ERRORS
This function may fail with the errors
.BR EACCES ,
.BR EPERM
and 
.BR EINVAL
as specified for the functions
.BR shmctl (3)
and
.BR semctl (3).
.SH SEE ALSO
.BR shr_chmod (3),
.BR shr_stat (3)
.SH AUTHORS
Principal author, Mattias Andrée.  See the LICENSE file for the full
list of authors.
.SH LICENSE
MIT/X Consortium License.
.SH BUGS
Please report bugs to https://github.com/maandree/shr/issues or to
maandree@member.fsf.org
