.TH SHR_KEY_TO_STR 3 SHR-%VERSION%
.SH NAME
.B shr_key_to_str
\- Convert a shared ring buffer key to a string.
.SH SYNOPSIS
.LP
.nf
#include <shr.h>
.P
__attribute__((nonnull))
void shr_key_to_str(const shr_key_t *restrict \fIkey\fP, char *restrict \fIstr\fP);
.fi
.P
Link with \fI\-lshr\fP.
.SH DESCRIPTION
The
.BR shr_key_to_str ()
function converts a shared ring buffer key to a string.
The key is read from \fIkey\fP and printed to \fIstr\fP.
.P
The length of \fIstr\fP is not checked, it should be allocated
with the size (\fISHR_KEY_STR_MAX\fP * sizeof(char)),
if not undefined behaviour is invoked if its allocation is too small.
.SH RETURN VALUES
None.
.SH ERRORS
All errors are ignored.
.SH SEE ALSO
.BR shr_remove_by_key (3),
.BR shr_open (3),
.BR shr_str_to_key (3)
.SH AUTHORS
Principal author, Mattias Andrée.  See the LICENSE file for the full
list of authors.
.SH LICENSE
MIT/X Consortium License.
.SH BUGS
Please report bugs to m@maandree.se
