.TH SHR_REMOVE_BY_KEY 3 SHR-%VERSION%
.SH NAME
.B shr_remove_by_key
\- Remove a shared ring buffer, without the need of opening it.
.SH SYNOPSIS
.LP
.nf
#include <shr.h>
.P
__attribute__((nonnull))
void shr_remove_by_key(const shr_key_t *restrict \fIkey\fP);
.fi
.P
Link with \fI\-lshr\fP.
.SH DESCRIPTION
The
.BR shr_remove_by_key ()
function removes a shared ring buffer, without the need of opening it.
.P
The key \fIkey\fP is used to identify the shared ring buffer that should
be removed.
.P
Undefined behaviour will be invoked if this function is called twice.
.SH RETURN VALUES
None.
.SH ERRORS
All errors are ignored.
.SH SEE ALSO
.BR shr_remove (3),
.BR shr_close (3)
.SH AUTHORS
Principal author, Mattias Andrée.  See the LICENSE file for the full
list of authors.
.SH LICENSE
MIT/X Consortium License.
.SH BUGS
Please report bugs to m@maandree.se
