.TH SHR_READ_DONE 3 SHR-%VERSION%
.SH NAME
.B shr_read_done
\- Epilogue for reading from a shared ring buffer.
.SH SYNOPSIS
.LP
.nf
#include <shr.h>
.P
__attribute__((nonnull))
int shr_read_done(shr_t *restrict \fIshr\fP);
.fi
.P
Link with \fI\-lshr\fP.
.SH DESCRIPTION
The
.BR shr_read_done ()
function mark the, by
.BR shr_read (),
.BR shr_read_try ()
or
.BR shr_read_timed (),
retrieve buffer as fully read.
.P
Undefined behaviour is invoked if multiple processes use this
function, even if not concurrently.
.SH RETURN VALUES
Upon successful completion, the function returns
either 1 or 0. 1 is returned if and only if all
available data has been read and the writer has
closed to access to the shared ring buffer.
Otherwise the function returns \-1 and sets
\fIerrno\fP to indicate the error.
.SH ERRORS
This function may fail with the errors
.BR EACCES ,
.BR EIDRM ,
.BR EINTR
and
.BR EINVAL ,
as specified for the function
.BR semop (3).
.SH SEE ALSO
.BR shr_open (3),
.BR shr_reverse_dup (3),
.BR shr_close (3),
.BR shr_read (3),
.BR shr_read_try (3),
.BR shr_read_timed (3),
.BR shr_write (3),
.BR shr_write_try (3),
.BR shr_write_timed (3),
.BR shr_write_done (3)
.SH AUTHORS
Principal author, Mattias Andrée.  See the LICENSE file for the full
list of authors.
.SH LICENSE
MIT/X Consortium License.
.SH BUGS
Please report bugs to m@maandree.se
